import type { ScenarioSpec } from "../../features/video-coach/types";

export const creditCardBooth: ScenarioSpec = {
  id: "credit-card-booth",
  title: "The Card Booth",
  jurisdiction: "SG",
  role: {
    name: "Marcus",
    descriptor: "Card promoter outside the MRT, friendly, on commission",
    goal: "Get you signed up today with the free gift and '$0 annual fee'",
  },
  learnerGoal: "Get the numbers that matter — APR, total cost, fees after year one — and leave without signing anything you haven't compared.",
  concepts: ["minimum-payment", "apr-total-cost"],
  facts: [
    "Typical card APR in SG is 26-28% on carried balances",
    "'No annual fee' usually means 'first year only'",
    "You can always take a brochure and apply online later — the offer rarely disappears",
  ],
  successCriteria: [
    "Ask for the APR or total borrowing cost, not just perks",
    "Ask what the minimum payment actually does to a carried balance",
    "Leave with information, not a signature made under time pressure",
  ],
  entryNodeId: "b1",
  relatedLessonId: "minimum-payment-trap",
  nodes: [
    {
      id: "b1",
      say: "Hi hi! Congrats — you qualify for our grad card! Free tumbler today only, no annual fee, and you just need 2 minutes and your IC. Student meal discounts too!",
      coachHint: "He's listing perks. None of the numbers that cost you money have been said yet — APR, late fees, fee after year one.",
      strategies: [
        "Ask the one question promoters rarely lead with: what's the interest rate on a carried balance?",
        "Slow the frame down: take the brochure, say you compare cards in writing.",
      ],
      choices: [
        {
          id: "a",
          label: "What's the interest rate if I carry a balance?",
          keywords: ["interest", "apr", "rate", "carry"],
          next: "b2-apr",
          quality: "strong",
          moves: [{ dimension: "information", label: "Asked for the APR before the perks" }],
        },
        {
          id: "b",
          label: "Free tumbler? Okay what do I need to do?",
          keywords: ["tumbler", "what do i need", "okay sure"],
          next: "b2-signup",
          quality: "weak",
          moves: [{ dimension: "decision", label: "Engaged on the gift, not the product" }],
        },
        {
          id: "c",
          label: "Not today, thanks — can I take a brochure?",
          keywords: ["brochure", "not today"],
          next: "b2-pushback",
          quality: "ok",
          moves: [{ dimension: "communication", label: "Declined and asked for written information" }],
        },
      ],
    },
    {
      id: "b2-apr",
      say: "Wah, most people ask about the miles first! It's ah... 26.8% per annum. But honestly nobody pays that — just pay the minimum every month, only 3%, super manageable.",
      coachHint: "There it is: 'just pay the minimum.' You know from the simulator what that does to $3,000 — five years of interest.",
      strategies: [
        "Ask what a $3,000 balance costs in total if you only pay minimums.",
        "Say the quiet part: minimum payments mostly service interest.",
      ],
      choices: [
        {
          id: "a",
          label: "If I carried $3,000 and paid only minimums, what would I pay in total by the end?",
          keywords: ["total", "in total", "by the end", "3000", "3,000"],
          next: "b3-total",
          quality: "strong",
          moves: [
            { dimension: "information", label: "Asked for total cost over the debt's life" },
            { dimension: "reasoning", label: "Converted an APR into a concrete outcome" },
          ],
        },
        {
          id: "b",
          label: "3% minimum? That does sound manageable.",
          keywords: ["manageable", "sounds ok", "sounds okay"],
          next: "b3-anchor",
          quality: "weak",
          moves: [{ dimension: "reasoning", label: "Accepted the minimum-payment frame" }],
        },
        {
          id: "c",
          label: "26.8% is steep. What's the annual fee after the first year?",
          keywords: ["annual fee", "after the first year", "year one"],
          next: "b3-fees",
          quality: "strong",
          moves: [{ dimension: "information", label: "Probed the post-promo fee structure" }],
        },
      ],
    },
    {
      id: "b2-signup",
      say: "Easy! IC and 3 minutes. I'll fill everything, you just sign here and here. The tumbler's yours either way — well, if you sign lah. 😄",
      coachHint: "You're at a signature with zero numbers discussed. Any question you ask now is worth more than the tumbler.",
      strategies: [
        "Stop and ask for the interest rate and fees before anything gets filled in.",
        "Take the form home — a legitimate offer survives overnight.",
      ],
      choices: [
        {
          id: "a",
          label: "Hold on — before I sign anything: what's the APR and what are the fees after year one?",
          keywords: ["before i sign", "apr", "fees"],
          next: "b3-fees",
          quality: "strong",
          moves: [{ dimension: "information", label: "Stopped the signature to get the numbers" }],
        },
        {
          id: "b",
          label: "Okay, here's my IC.",
          keywords: ["here's my ic", "heres my ic", "okay sign"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "decision", label: "Signed without knowing the cost of the product" }],
        },
        {
          id: "c",
          label: "Can I take the form and read it tonight?",
          keywords: ["take the form", "read it", "tonight"],
          next: "b3-urgency",
          quality: "ok",
          moves: [{ dimension: "decision", label: "Created space to read before signing" }],
        },
      ],
    },
    {
      id: "b2-pushback",
      say: "Sure, sure... but the tumbler promo ends today, and honestly the counter offer next month is worse. You're literally leaving money on the table!",
      pressure: "urgency",
      coachHint: "The 'gift expires today' is the whole play. The card will exist tomorrow; the tumbler is $8 at Daiso.",
      strategies: [
        "Hold: information first, gifts never factor into borrowing decisions.",
        "Ask him to circle the APR and fees on the brochure so tonight's comparison is easy.",
      ],
      choices: [
        {
          id: "a",
          label: "The tumbler's not part of my decision. Circle the APR and year-two fee on this and I'll compare tonight.",
          keywords: ["circle", "compare tonight", "not part of my decision"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "resilience", label: "Discounted the gift from the decision" },
            { dimension: "information", label: "Left with the exact numbers to compare" },
          ],
        },
        {
          id: "b",
          label: "Hmm, if it ends today... okay maybe just sign me up.",
          keywords: ["ends today", "sign me up"],
          next: "b2-signup",
          quality: "weak",
          moves: [{ dimension: "resilience", label: "The expiring gift flipped the decision" }],
        },
        {
          id: "c",
          label: "Then I'll leave the money on the table. Have a good one!",
          keywords: ["leave the money", "have a good one", "bye"],
          next: "end:goal_met",
          quality: "ok",
          moves: [{ dimension: "communication", label: "Exited cleanly under a pressure line" }],
        },
      ],
    },
    {
      id: "b3-total",
      say: "Eh, that's ah... not a number we really calculate here. But seriously, nobody carries $3,000 forever lah! Look, sign today and I'll throw in extra 5,000 miles.",
      pressure: "anchoring",
      coachHint: "He can't answer the total-cost question — that silence IS the answer. The miles are a distraction from an unanswered number.",
      strategies: [
        "Name the non-answer: if the seller can't state total cost, compare elsewhere in writing.",
        "Keep the door open but on your terms: brochure, tonight, side-by-side.",
      ],
      choices: [
        {
          id: "a",
          label: "If the total cost isn't answerable at the booth, I'll compare cards in writing tonight. Thanks Marcus.",
          keywords: ["in writing", "compare", "tonight"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "reasoning", label: "Treated an unanswerable total as disqualifying" },
            { dimension: "resilience", label: "Miles bonus didn't reopen the decision" },
          ],
        },
        {
          id: "b",
          label: "5,000 miles though... okay, where do I sign?",
          keywords: ["miles", "where do i sign"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "decision", label: "A perk outweighed an unanswered cost question" }],
        },
      ],
    },
    {
      id: "b3-anchor",
      say: "Right?? $90 on $3,000 — anyone can afford that! So, IC? I can have you approved before your train comes.",
      pressure: "anchoring",
      coachHint: "$90/month on $3,000 at 26.8% runs about five years. 'Affordable monthly' is the anchor hiding the total.",
      strategies: [
        "Do the five-year math out loud — the anchor breaks when the total appears.",
        "Step back to the question that matters: total repaid, not monthly comfort.",
      ],
      choices: [
        {
          id: "a",
          label: "$90 a month on $3,000 at that rate is about five years of payments. That's the number that matters — and it's a no.",
          keywords: ["five years", "5 years", "that's a no", "thats a no"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "reasoning", label: "Broke the monthly anchor with the total timeline" },
            { dimension: "decision", label: "Decided on total cost, stated clearly" },
          ],
        },
        {
          id: "b",
          label: "Before my train comes? Okay okay, here.",
          keywords: ["okay here", "before my train"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "resilience", label: "Time pressure closed the deal" }],
        },
        {
          id: "c",
          label: "Affordable per month isn't the same as cheap. What's the total repaid?",
          keywords: ["total repaid", "not the same as cheap"],
          next: "b3-total",
          quality: "strong",
          moves: [{ dimension: "reasoning", label: "Separated monthly affordability from total cost" }],
        },
      ],
    },
    {
      id: "b3-fees",
      say: "First year free! Second year it's $196.20, but just call to waive lah, everyone does. So — shall we? Train's coming. 😉",
      coachHint: "You got the real numbers: 26.8% APR, $196.20 year-two fee, 'call to waive' (not guaranteed). That's everything you came for.",
      strategies: [
        "Close with the numbers in hand: compare tonight, apply online if it wins.",
        "Confirm the waiver isn't guaranteed — 'usually waived' is not a term.",
      ],
      choices: [
        {
          id: "a",
          label: "26.8% and $196.20 from year two — got it. I'll compare tonight and apply online if this wins.",
          keywords: ["compare tonight", "apply online", "got it"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "information", label: "Collected APR and post-promo fee before deciding" },
            { dimension: "decision", label: "Deferred to a written comparison on your timeline" },
          ],
        },
        {
          id: "b",
          label: "Is the waiver guaranteed in writing, or just 'usually'?",
          keywords: ["guaranteed", "in writing", "usually"],
          next: "end:goal_met",
          quality: "strong",
          moves: [{ dimension: "information", label: "Tested a verbal promise against written terms" }],
        },
        {
          id: "c",
          label: "Eh fine, the fee's waivable anyway. Sign me up.",
          keywords: ["waivable anyway", "sign me up"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "decision", label: "Relied on an unguaranteed verbal waiver" }],
        },
      ],
    },
    {
      id: "b3-urgency",
      say: "Can, can... but honestly the promo code expires when my shift ends. If you apply at home it's the normal offer — no tumbler, no bonus miles. Sure or not?",
      pressure: "urgency",
      coachHint: "He just confirmed the product survives overnight — only the trinkets expire. That's your answer.",
      strategies: [
        "Accept losing the trinkets explicitly — that reframes 'losing the promo' as a tiny cost.",
        "Verify what actually differs in the at-home offer: rate and fees, or just gifts?",
      ],
      choices: [
        {
          id: "a",
          label: "So the rate and fees are identical at home — only the tumbler differs? Perfect, I'll read it tonight.",
          keywords: ["identical", "only the tumbler", "read it tonight"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "information", label: "Verified what the 'expiring offer' actually contains" },
            { dimension: "resilience", label: "Traded trinkets for reading time without hesitation" },
          ],
        },
        {
          id: "b",
          label: "Ah no tumbler then... okay fine, sign me up now.",
          keywords: ["no tumbler", "fine sign"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "resilience", label: "Loss-framing on a free gift closed the deal" }],
        },
      ],
    },
  ],
};
