import type { ScenarioSpec } from "../../features/video-coach/types";

export const friendExpensiveWeekend: ScenarioSpec = {
  id: "friend-expensive-weekend",
  title: "The Expensive Weekend",
  jurisdiction: "SG",
  role: {
    name: "Jamie",
    descriptor: "Your uni friend, group-chat energy, genuinely likes you",
    goal: "Get you to commit to a $650+ Bali trip tonight",
  },
  learnerGoal: "Keep both the friendship and your payday plan — decline or reshape the plan without caving or ghosting.",
  concepts: ["pay-yourself-first", "budget-shock"],
  facts: [
    "You just routed $500 to savings on payday",
    "Your flexible budget this month is about $300",
    "You do want to see these friends",
  ],
  successCriteria: [
    "Ask for the real all-in cost before deciding",
    "State your boundary with a reason, not an apology spiral",
    "Offer or accept an alternative inside your budget",
  ],
  entryNodeId: "n1",
  relatedLessonId: "night-it-lands",
  nodes: [
    {
      id: "n1",
      say: "Eh!! We're booking Bali for the long weekend — flights plus villa, like $650 each. Everyone's in already. You just got paid right? 😏",
      coachHint: "Before yes or no: you don't actually know the real cost yet. '$650' is never the whole number.",
      strategies: [
        "Ask for the all-in total first — flights, villa, food, transport — before any commitment.",
        "Lead with your plan: you routed savings on payday, so the question is what fits the remainder.",
      ],
      choices: [
        {
          id: "a",
          label: "Sounds amazing! Book me in.",
          keywords: ["book me", "i'm in", "im in", "sounds amazing", "yes let", "lets go", "let's go"],
          next: "n2-cave",
          quality: "weak",
          moves: [{ dimension: "decision", label: "Committed before knowing the total cost" }],
        },
        {
          id: "b",
          label: "How much all-in — flights, villa, food, everything?",
          keywords: ["how much", "total", "all-in", "all in", "everything", "cost"],
          next: "n2-total",
          quality: "strong",
          moves: [{ dimension: "information", label: "Asked for the total cost before deciding" }],
        },
        {
          id: "c",
          label: "Can't make it this time, sorry.",
          keywords: ["can't", "cant", "no ", "sorry"],
          next: "n2-pushback",
          quality: "ok",
          moves: [{ dimension: "communication", label: "Set a boundary (without a reason yet)" }],
        },
      ],
    },
    {
      id: "n2-total",
      say: "Uhh flights are 280, villa share maybe 250... plus food and scooters and stuff. Okay maybe like 800 total? But it's worth it!",
      coachHint: "Now you have a real number: $800 against $300 flexible. The math is your reason — use it, kindly.",
      strategies: [
        "Compare the number to your flexible budget out loud, then offer something inside it.",
        "Thank them for the honesty, decline the trip specifically, keep the friendship general.",
      ],
      choices: [
        {
          id: "a",
          label: "That's my whole savings this month. I'm out for Bali — but I'm in for a day trip.",
          keywords: ["day trip", "i'm out", "im out", "savings", "budget", "instead"],
          next: "n3-alt",
          quality: "strong",
          moves: [
            { dimension: "reasoning", label: "Compared cost to actual flexible budget" },
            { dimension: "communication", label: "Boundary plus alternative in one sentence" },
          ],
        },
        {
          id: "b",
          label: "$800?! Who pays that for a weekend, that's insane.",
          keywords: ["insane", "crazy", "who pays", "ridiculous"],
          next: "n3-defensive",
          quality: "weak",
          moves: [{ dimension: "communication", label: "Judged the plan instead of stating your constraint" }],
        },
        {
          id: "c",
          label: "Hmm, okay. Let me think about it.",
          keywords: ["think about", "maybe", "not sure"],
          next: "n3-pressure",
          quality: "ok",
          moves: [{ dimension: "decision", label: "Deferred without a criterion or deadline" }],
        },
      ],
    },
    {
      id: "n2-cave",
      say: "Yesss! Okay send me $650 by tonight so I can lock the villa 🙏",
      coachHint: "Commitment isn't payment yet. You can still check the month before money moves.",
      strategies: [
        "Pause the transfer: say you need to run your month's numbers first, tonight.",
        "Be direct: first paycheck, you have a routing plan, and this doesn't fit it.",
      ],
      choices: [
        {
          id: "a",
          label: "Tonight? Wait — let me check my month first, I'll text you after dinner.",
          keywords: ["check my month", "numbers", "let me check", "after dinner"],
          next: "n3-pressure",
          quality: "ok",
          moves: [{ dimension: "decision", label: "Recovered a checkpoint before paying" }],
        },
        {
          id: "b",
          label: "Sure, sending now.",
          keywords: ["sending", "sure", "paynow", "transferred"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "decision", label: "Paid without checking the month" }],
        },
        {
          id: "c",
          label: "Actually — honest moment. First paycheck, I have a plan for it, and $650 breaks it. I can't.",
          keywords: ["honest", "plan", "can't afford", "cant afford", "breaks it"],
          next: "n3-alt",
          quality: "strong",
          moves: [
            { dimension: "communication", label: "Reversed a bad commitment honestly" },
            { dimension: "resilience", label: "Chose short-term awkwardness over a broken plan" },
          ],
        },
      ],
    },
    {
      id: "n2-pushback",
      say: "Wah, instant reject! Come on, it's once a year. Friendship more than money right? 🥺",
      pressure: "guilt",
      coachHint: "Guilt reframes a budget decision as a loyalty test. It isn't. Answer the loyalty part warmly and hold the money part firmly.",
      strategies: [
        "Separate the two: big yes to the friends, no to this price tag — then offer what fits.",
        "Name your plan as the reason. A reason isn't an excuse.",
      ],
      choices: [
        {
          id: "a",
          label: "It's not the trip, it's my payday plan — savings route first. I'm in for something smaller.",
          keywords: ["payday plan", "savings route", "something smaller", "not the trip"],
          next: "n3-alt",
          quality: "strong",
          moves: [
            { dimension: "resilience", label: "Held the boundary through a guilt frame" },
            { dimension: "reasoning", label: "Gave the mechanism, not an excuse" },
          ],
        },
        {
          id: "b",
          label: "Okay okay fine... I'll come.",
          keywords: ["fine", "i'll come", "ill come", "okay okay"],
          next: "n2-cave",
          quality: "weak",
          moves: [{ dimension: "resilience", label: "Dropped the boundary at the first push" }],
        },
        {
          id: "c",
          label: "Friendship doesn't cost $800 lah.",
          keywords: ["doesn't cost", "doesnt cost"],
          next: "n3-alt",
          quality: "ok",
          moves: [{ dimension: "communication", label: "Deflected the guilt with humor" }],
        },
      ],
    },
    {
      id: "n3-pressure",
      say: "Okay but the villa price goes UP at midnight. Everyone's waiting on you. Decide now can? ⏰",
      pressure: "urgency",
      coachHint: "A real deadline plus social proof — the classic combination. If a decision must be instant, 'no' is always a safe instant answer.",
      strategies: [
        "Name the tactic: anything that needs an answer this second is a no by default.",
        "Give a concrete decision time that's yours, not theirs.",
      ],
      choices: [
        {
          id: "a",
          label: "If it needs an answer right now, it's a no. If plans hold tomorrow, I'm in for a day trip.",
          keywords: ["right now", "it's a no", "its a no", "day trip"],
          next: "end:goal_met",
          quality: "strong",
          moves: [
            { dimension: "resilience", label: "Refused to decide under artificial urgency" },
            { dimension: "decision", label: "Converted pressure into a clear default" },
          ],
        },
        {
          id: "b",
          label: "Ugh, fine, book it.",
          keywords: ["book it", "fine"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "resilience", label: "Urgency overrode the criteria" }],
        },
        {
          id: "c",
          label: "I'll check my numbers after dinner and text you by 9. That's the best I can do.",
          keywords: ["by 9", "after dinner", "text you"],
          next: "end:goal_met",
          quality: "ok",
          moves: [{ dimension: "decision", label: "Set your own decision deadline" }],
        },
      ],
    },
    {
      id: "n3-alt",
      say: "Hmm okay okay. A day thing could be fun actually... Sentosa Saturday? Like $60 with food?",
      coachHint: "This is the win condition arriving. Confirm with your number so the agreement is concrete.",
      strategies: [
        "Accept with the number out loud — it locks the plan and normalizes budget talk.",
        "Accept warmly and appreciate that they flexed.",
      ],
      choices: [
        {
          id: "a",
          label: "$60 fits my fun budget exactly. Locked. 🎉",
          keywords: ["fits", "locked", "60", "budget"],
          next: "end:goal_met",
          quality: "strong",
          moves: [{ dimension: "decision", label: "Closed on an alternative consistent with the stated budget" }],
        },
        {
          id: "b",
          label: "Deal! And thanks for getting it.",
          keywords: ["deal", "thanks"],
          next: "end:goal_met",
          quality: "ok",
          moves: [{ dimension: "communication", label: "Confirmed the plan and preserved the relationship" }],
        },
      ],
    },
    {
      id: "n3-defensive",
      say: "Wow, okay. It's just money lah — we're only young once, you know?",
      coachHint: "You judged their plan, they got defensive. A small repair reopens the door without reopening your wallet.",
      strategies: [
        "Repair first ('not dumb — just outside my plan'), then re-offer the alternative.",
        "Hold the boundary but drop the judgment: it's about your month, not their choices.",
      ],
      choices: [
        {
          id: "a",
          label: "Sorry — that came out wrong. It's not a dumb plan, it's just outside my month. Day trip instead?",
          keywords: ["came out wrong", "sorry", "outside my", "day trip"],
          next: "n3-alt",
          quality: "strong",
          moves: [{ dimension: "communication", label: "Repaired the tone while keeping the boundary" }],
        },
        {
          id: "b",
          label: "Whatever. Do what you want.",
          keywords: ["whatever"],
          next: "end:impasse",
          quality: "weak",
          moves: [{ dimension: "communication", label: "Let the conversation collapse" }],
        },
        {
          id: "c",
          label: "YOLO isn't a budget strategy, Jamie.",
          keywords: ["yolo"],
          next: "n3-pressure",
          quality: "ok",
          moves: [{ dimension: "reasoning", label: "Pushed back on the frame, if a bit sharp" }],
        },
      ],
    },
  ],
};
